name: Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.11.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          cache: true

      - name: Configure project
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build project
        run: cmake --build build --config Release

      - name: Run unit tests
        run: ctest --test-dir build -C Release --output-on-failure